### ISSUE TITLE
What does Sequence_Mask?

### ISSUE THREAD

**Issue by RH1994R** [luozhouyang/keras-crf#3]
Could someone explain to me why you need that Sequence Mask for using this crf layer? What is the purpose of it? 
I would highly appreciate your help.

**Comment by luozhouyang** [comment]
`CRF` layer needs `sequence_mask` to compute `sequence_length` correctly.

**Comment by RH1994R** [comment]
Ok thanks. Can you explain what that means in detail?

**Comment by luozhouyang** [comment]
I remove the `mask` argument now, you can found new example in README
